"""Add document_text model one to one field for documet

Revision ID: b4980f087989
Revises: e9e0ddbce572
Create Date: 2026-10-07 12:43:06.237363

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4980f087989'
down_revision: Union[str, Sequence[str], None] = 'e9e0ddbce572'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

document_status = sa.Enum(
    'uploaded',
    'processing',
    'ready',
    'failed',
    name='documentstatus',
)


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    
    if bind.dialect.name == 'postgresql':
        document_status.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_text',
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('document_id')
    )
    op.add_column('documents', sa.Column('status', sa.Enum('uploaded', 'processing', 'ready', 'failed', name='documentstatus'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'status')
    op.drop_table('document_text')
    if bind.dialect.name == 'postgresql':
        document_status.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
